### ISSUE TITLE
problem in start service

### ISSUE THREAD

**Issue by james12974** [seriyps/mtproto_proxy#1]
Hey when i run `sudo systemctl start mtproto-proxy`i have this problem:
`Warning: The unit file, source configuration file or drop-ins of mtproto-proxy.service changed on disk. Run 'systemctl daemon-reload' to reload units.
`
and when i run `systemctl daemon-reload` problem still exist.
Can you tell me how i can fix it?

**Comment by seriyps** [comment]
Hi. It's not a problem at all, but warning. Can be fixed (as suggested by warning message) by running `sudo systemctl daemon-reload` each time you re-install the proxy

**Comment by james12974** [comment]
I ignored it but proxy did not run at all and i cant connect in the client.
i run `sudo systemctl status mtproto-proxy`
and this is result : 
` Loaded: loaded (/opt/mtp_proxy/bin/mtp_proxy; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-10-21 18:08:21 CEST; 19s ago
  Process: 6781 ExecStart=/opt/mtp_proxy/bin/mtp_proxy foreground (code=exited, sta Main PID: 6781 (code=exited, status=203/EXEC)`
and i have checked the mtproto-proxy.service the folder with destination /opt/mtp_proxy/bin/mtp_proxy for Execstart didnt create after make install.
after i create this destination manually the error with `systemctl daemon-reload` thats gone but proxy still didnt run.

**Comment by seriyps** [comment]
Can you show output of `make && sudo make install`?

вс, 21 окт. 2018 г., 18:17 james12974 notifications@github.com:

**Comment by james12974** [comment]
yup
this is the result
`./rebar3 as prod release
===> Verifying dependencies...
===> Package lager-3.6.3 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /root/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to /root/.cache/rebar3/hex/default/packages.idx
===> Fetching lager ({pkg,<<"lager">>,<<"3.6.3">>})
===> Downloaded package, caching at /root/.cache/rebar3/hex/default/packages/lager-3.6.3.tar
===> Linking _build/default/lib/lager to _build/prod/lib/lager
===> Fetching ranch ({pkg,<<"ranch">>,<<"1.5.0">>})
===> Downloaded package, caching at /root/.cache/rebar3/hex/default/packages/ranch-1.5.0.tar
===> Linking _build/default/lib/ranch to _build/prod/lib/ranch
===> Fetching goldrush ({pkg,<<"goldrush">>,<<"0.1.9">>})
===> Downloaded package, caching at /root/.cache/rebar3/hex/default/packages/goldrush-0.1.9.tar
===> Linking _build/default/lib/goldrush to _build/prod/lib/goldrush
===> Compiling ranch
===> Compiling goldrush
===> Compiling lager
===> Compiling mtproto_proxy
src/mtp_config.erl:49: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
src/mtp_config.erl:60: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1

===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /root/mtproto_proxy/_build/prod/lib
          /usr/lib/erlang/lib
===> Resolved mtp_proxy-0.1.0
===> Including Erts from /usr/lib/erlang
===> release successfully created!
mkdir -p //var/log/mtproto-proxy
chown mtproto-proxy //var/log/mtproto-proxy
chown: invalid user: ‘mtproto-proxy’
Makefile:20: recipe for target '//var/log/mtproto-proxy' failed
make: *** [//var/log/mtproto-proxy] Error 1`

**Comment by seriyps** [comment]
Ah, I see now. There is an error in Makefule. I will fix soon

**Comment by james12974** [comment]
problem in make is ok
but i have still `systemctl daemon-reload` warning and proxy wont start .
can you fix this or i can give you the server login details

**Comment by seriyps** [comment]
daemon-reload worning is not a problem at all.
Can you show output from make againg?
Let's try to solve it here, and if it will not work out, I can try to fix it on your server

**Comment by james12974** [comment]
./rebar3 as prod release
===> Verifying dependencies...
===> Compiling mtproto_proxy
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /root/mtproto_proxy/_build/prod/lib
          /usr/lib/erlang/lib
          /root/mtproto_proxy/_build/prod/rel
===> Resolved mtp_proxy-0.1.0
===> Including Erts from /usr/lib/erlang
===> release successfully created!
sudo useradd -r mtproto-proxy || true
useradd: user 'mtproto-proxy' already exists
mkdir -p /opt/mtp_proxy
cp -n -r _build/prod/rel/mtp_proxy /opt/mtp_proxy
mkdir -p /opt/mtp_proxy/log
chmod 777 /opt/mtp_proxy/log
install -D config/mtproto-proxy.service /etc/systemd/system/mtproto-proxy.service
systemctl daemon-reload
this is the result.
ummm seems still make cant  create this directory /opt/mtp_proxy/bin/mtp_proxy

**Comment by james12974** [comment]
If you can pls give me your telegram id so we can talk about it faster.

**Comment by seriyps** [comment]
@seriy_ps
