### ISSUE TITLE
process crash on Debian 9

### ISSUE THREAD

**Issue by SmOkEnksp** [seriyps/mtproto_proxy#10]
"Kernel pid terminated",application_controller,"{application_start_failure,mtproto_proxy,{{shutdown,{failed_to_start_child,mtp_config,{undef,[{string,lexemes,[\"# force_probability 10 10\ndefault 2;

**Comment by SmOkEnksp** [comment]
i am install fresh version of Erlang, proxy start but didnt work.
in app log i have mtp_handler:handle_info:118 handle_data error unknown_protocol

**Comment by seriyps** [comment]
Looking at the stacktrace you posted in 1st message I could say that your
Erlang version is not fresh enough.
You need at least Erlang 20

вт, 2 апр. 2019 г., 23:23 SmOkEnksp <notifications@github.com>:

**Comment by SmOkEnksp** [comment]
already try install new version on my debian but unsuccessfully :(

**Comment by seriyps** [comment]
And you installed proxy using instructions from readme? Have you changed the config file in any way?

**Comment by SmOkEnksp** [comment]
> And you installed proxy using instructions from readme? Have you changed the config file in any way?

yes, install with instructions and change config. on other server with ubuntu proxy work amazing.

**Comment by seriyps** [comment]
> mtp_handler:handle_info:118 handle_data error unknown_protocol

Well, it's difficult to tell what might be the reason for this error. In general it means that first 64 bytes of data that proxy received from client is unexpected. It might be that proxy secret is invalid.

**Comment by SmOkEnksp** [comment]
maybe if i am uninstall erlang and reinstall, script automatic install dependencies?

**Comment by seriyps** [comment]
are you sure you use correct secret when connecting to proxy?

**Comment by SmOkEnksp** [comment]
> are you sure you use correct secret when connecting to proxy?

tomorrow i try again

**Comment by SmOkEnksp** [comment]
{"could not start kernel pid",application_controller,"invalid config data: application: allowed_protocols; invalid parameter: mtp_secure"}
idk whats wrong

**Comment by seriyps** [comment]
I guess there is some syntax error in config file. Can you show your config?

**Comment by SmOkEnksp** [comment]
> I guess there is some syntax error in config file. Can you show your config?

%% -*- mode: erlang -*-
[
 {allowed_protocols, [mtp_secure]},
 {mtproto_proxy,
  %% see src/mtproto_proxy.app.src for examples.
  %% DO NOT EDIT src/mtproto_proxy.app.src!!!
  [
    {ports,
     [#{name => mtp_handler1,
        listen_ip => "0.0.0.0",
        port => 7777,
        secret => <<"secret">>,
        tag => <<"chan_tag">>}
     ]}
   ]},

 %% Logging config
 {lager,
  [{log_root, "/var/log/mtproto-proxy"},
   {crash_log, "crash.log"},
   {handlers,
    [
     {lager_console_backend,
      [{level, critical}]},

     {lager_file_backend,
      [{file, "application.log"},
       {level, info},

       %% Do fsync only on critical messages
       {sync_on, critical},
       %% If we logged more than X messages in a second, flush the rest
       {high_water_mark, 300},
       %% If we hit hwm and msg queue len is >X, flush the queue
       {flush_queue, true},
       {flush_threshold, 2000},
       %% How often to check if log should be rotated
       {check_interval, 5000},
       %% Rotate when file size is 100MB+
       {size, 104857600}
      ]}
    ]}]},
 {sasl,
  [{errlog_type, error}]}
].

**Comment by seriyps** [comment]
Yep, you put `allowed_protocols` to wrong place. Should be

```
%% -*- mode: erlang -*-
[
 {mtproto_proxy,
  %% see src/mtproto_proxy.app.src for examples.
  %% DO NOT EDIT src/mtproto_proxy.app.src!!!
  [
    {allowed_protocols, [mtp_secure]},
    {ports,
     [#{name => mtp_handler1,
        listen_ip => "0.0.0.0",
        port => 7777,
        secret => <<"secret">>,
        tag => <<"chan_tag">>}
     ]}
   ]},

 %% Logging config
 {lager,
  [{log_root, "/var/log/mtproto-proxy"},
   {crash_log, "crash.log"},
   {handlers,
    [
     {lager_console_backend,
      [{level, critical}]},

     {lager_file_backend,
      [{file, "application.log"},
       {level, info},

       %% Do fsync only on critical messages
       {sync_on, critical},
       %% If we logged more than X messages in a second, flush the rest
       {high_water_mark, 300},
       %% If we hit hwm and msg queue len is >X, flush the queue
       {flush_queue, true},
       {flush_threshold, 2000},
       %% How often to check if log should be rotated
       {check_interval, 5000},
       %% Rotate when file size is 100MB+
       {size, 104857600}
      ]}
    ]}]},
 {sasl,
  [{errlog_type, error}]}
].
```

**Comment by SmOkEnksp** [comment]
thanks, now it works!

**Comment by SmOkEnksp** [comment]
2019-05-12 04:26:35 =CRASH REPORT====
  crasher:
    initial call: mtp_config:init/1
    pid: <0.532.0>
    registered_name: []
    exception exit: {{undef,[{string,lexemes,["# force_probability 10 10\ndefault 2;\nproxy_for 1 149.154.175.50:8888;\nproxy_for -1 149.154.175.50:8888;\nproxy_for 2$
    ancestors: [mtproto_proxy_sup,<0.530.0>]
    messages: []
    links: [<0.531.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 1118
  neighbours:
2019-05-12 04:26:35 =SUPERVISOR REPORT====
     Supervisor: {local,mtproto_proxy_sup}
     Context:    start_error
     Reason:     {undef,[{string,lexemes,["# force_probability 10 10\ndefault 2;\nproxy_for 1 149.154.175.50:8888;\nproxy_for -1 149.154.175.50:8888;\nproxy_for 2 149$
     Offender:   [{pid,undefined},{id,mtp_config},{mfargs,{mtp_config,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

**Comment by SmOkEnksp** [comment]
cat /var/log/mtproto-proxy/application.log
2019-05-12 04:26:35.077 [info] <0.443.0> Application lager started on node 'mtproto_proxy@0.0.0.0'
2019-05-12 04:26:35.180 [error] <0.532.0>@string:lexemes CRASH REPORT Process <0.532.0> with 0 neighbours exited with reason: call to undefined function string:lexemes("# force_probability 10 10\ndefault 2;\nproxy_for 1 149.154.175.50:8888;\nproxy_for -1 149.154.175....", "\n") in gen_server:init_it/6 line 352
2019-05-12 04:26:35.180 [error] <0.531.0>@string:lexemes Supervisor mtproto_proxy_sup had child mtp_config started with mtp_config:start_link() at undefined exit with reason call to undefined function string:lexemes("# force_probability 10 10\ndefault 2;\nproxy_for 1 149.154.175.50:8888;\nproxy_for -1 149.154.175....", "\n") in context start_error

**Comment by seriyps** [comment]
Make sure you use erlang 20 or 21
