### ISSUE TITLE
make && make install wont work

### ISSUE THREAD

**Issue by kooran** [seriyps/mtproto_proxy#13]
i get this error when use "make && make install" command:

./rebar3 as prod release
===> Rebar dependency crypto could not be loaded for reason {"no such file or directory",
                                                                    "crypto.app"}
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by kooran** [comment]
i don't know what i've missed , but with reinstalling the OS the issue has been solved.

**Comment by seriyps** [comment]
`crypto.app` most likely tells that `libssl-dev` package was not installed

**Comment by goaryan1** [comment]
> `crypto.app` most likely tells that `libssl-dev` package was not installed

Did not work for me, still getting the same error.
