### ISSUE TITLE
Fake TLS Client

### ISSUE THREAD

**Issue by kooran** [seriyps/mtproto_proxy#14]
How a client can connect with TLS fake protocol enabled? everything works fine but when i use allowed protocol fake TLS, none of telegram versions can connect, i have tested it even on beta versions

**Comment by seriyps** [comment]
1) You need telegram desktop beta 1.7.15
2) You need to use `fake-tls` git branch of mtproto proxy (because it's still experimental).
3) You have to use "base64-encoded" secret. It looks smth like this: `7nJlZHNmmrzaok4G4Tecra9lbi53aWtpcGVkaWEub3Jn` (starts with `7` and contains lowercase and uppercase letters and digits) and proxy link should be printed by proxy AND also logged to `/var/log/mtproto-proxy/application.log`

**Comment by seriyps** [comment]
Simple way to generate TLS secret with Python:

```
$ python3
> import binascii
> import base64
> base64.urlsafe_b64encode(b'\xee' + binascii.a2b_hex("72656473669abcdaa24e06e1379cadaf") + b'google.com')
b'7nJlZHNmmrzaok4G4Tecra9nb29nbGUuY29t'
```

**Comment by Morrigan-Ship** [comment]
how to decode base64 secret code?
like this:

https://t.me/proxy?server=188.213.0.185&port=8085&secret=FgMBAgABAAH8AwOG4kw63Q==
secret="FgMBAgABAAH8AwOG4kw63Q=="

i tried to decode it but its cannot because its binary
can anyone help?

**Comment by ferimanam** [comment]
> how to decode base64 secret code? like this:
> 
> https://t.me/proxy?server=188.213.0.185&port=8085&secret=FgMBAgABAAH8AwOG4kw63Q== secret="FgMBAgABAAH8AwOG4kw63Q=="
> 
> i tried to decode it but its cannot because its binary can anyone help?

When using the secret code, it is better to use the word 7

**Comment by seriyps** [comment]
> how to decode base64 secret code? like this:
> 
> https://t.me/proxy?server=188.213.0.185&port=8085&secret=FgMBAgABAAH8AwOG4kw63Q== secret="FgMBAgABAAH8AwOG4kw63Q=="
> 
> i tried to decode it but its cannot because its binary can anyone help?

You can try to use this tool http://seriyps.ru/mtpgen.html

But it looks like your example has incorrect secret

**Comment by Morrigan-Ship** [comment]
> But it looks like your example has incorrect secret

its correct its new version of MTproto

**Comment by seriyps** [comment]
> > But it looks like your example has incorrect secret
> 
> its correct its new version of MTproto

Interesting! Do you know how it works? What protocol does it use?

**Comment by Morrigan-Ship** [comment]
no

**Comment by mehdimmd81** [comment]
> > > But it looks like your example has incorrect secret
> > 
> > 
> > its correct its new version of MTproto
> 
> Interesting! Do you know how it works? What protocol does it use?

yes 

import base64

# داده Base64 URL-safe
secret_base64_url_safe = "FgMBAgABAAH8AwOG4kw63Q=="

# تبدیل Base64 URL-safe به Base64 استاندارد
base64_standard = secret_base64_url_safe.replace('_', '/').replace('-', '+')

# افزودن پدینگ (برای طول مضرب از 4)
padding = len(base64_standard) % 4
if padding != 0:
    base64_standard += '=' * (4 - padding)

try:
    # دکد Base64
    decoded_bytes = base64.b64decode(base64_standard)
    print(f"Decoded bytes: {decoded_bytes}")

    # نمایش بایت‌ها به صورت رشته هگزادسیمال
    hex_representation = decoded_bytes.hex()
    print(f"Hexadecimal representation: {hex_representation}")
    
    # نمایش بایت‌ها به صورت متنی (اگر قابل تبدیل باشد)
    try:
        decoded_str = decoded_bytes.decode('utf-8', errors='ignore')
        print(f"Decoded string: {decoded_str}")
    except UnicodeDecodeError:
        print("Decoded bytes are not valid UTF-8 text.")
except Exception as e:
    print(f"Error decoding Base64: {e}")

**Comment by mehdimmd81** [comment]
yes

import base64

# URL-safe Base64 data
secret_base64_url_safe = "FgMBAgABAAH8AwOG4kw63Q=="

# Convert URL-safe Base64 to standard Base64
base64_standard = secret_base64_url_safe.replace('_', '/').replace('-', '+')

# Add padding (for length multiples of 4)
padding = len(base64_standard) % 4
if padding != 0:
 base64_standard += '=' * (4 - padding)

try:
 # Base64 codec
 decoded_bytes = base64.b64decode(base64_standard)
 print(f"Decoded bytes: {decoded_bytes}")

 # Display bytes as a hexadecimal string
 hex_representation = decoded_bytes.hex()
 print(f"Hexadecimal representation: {hex_representation}")

 # Display bytes as text (if convertible)
 try:
 decoded_str = decoded_bytes.decode('utf-8', errors='ignore')
 print(f"Decoded string: {decoded_str}")
 except UnicodeDecodeError:
 print("Decoded bytes are not valid UTF-8 text.")
except Exception as e:
 print(f"Error decoding Base64: {e}")

**Comment by mehdimmd81** [comment]
If you update the script, instead of fake fear, instead of the letter ****, we use this attitude symbol, it will be filtered later

> Reference in ne
