### ISSUE TITLE
Problems on uploading pictures

### ISSUE THREAD

**Issue by HirbodBehnam** [seriyps/mtproto_proxy#16]
Hello
I installed the fake-tls branch and everything works fine except that with fake-tls I cannot upload photos. (But I can with secure mode with dd).
Also the [alexbers](https://github.com/alexbers/mtprotoproxy) source works correctly.

**Comment by seriyps** [comment]
Thanks! I'll look at it.

пт, 9 авг. 2019 г., 17:32 Hirbod Behnam <notifications@github.com>:

**Comment by seriyps** [comment]
It's fixed now. Thank you for your report!

**Comment by HirbodBehnam** [comment]
Thanks it's working now!
