### ISSUE TITLE
change config file without reinstall script

### ISSUE THREAD

**Issue by mohamad77** [seriyps/mtproto_proxy#17]
Hello
you said :
> There are other ways as well. It's even possible to update configuration options without service restart / without downtime, but it's a bit trickier.'

please explain this method.
also how can i limit or view connections number( or client ips ) on each port?
cal we use one port with multi secret?

thanks

**Comment by seriyps** [comment]
Well, it actually depends on which config key you want to update. Some of them can be updated just like this (change allowed protocol):

```bash
/opt/mtp_proxy/bin/mtp_proxy eval 'application:set_env(mtproto_proxy, allowed_protocols, [mtp_fake_tls]).'
```

Some of them require some extra reconfiguration being triggered (change max number of connections):

```bash
/opt/mtp_proxy/bin/mtp_proxy eval 'K = max_connections, V = 64000, application:set_env(mtproto_proxy, K, V), mtproto_proxy_app:config_change([{K, V}], [], []).'
```

But those changes won't survive service restart. If you want those config changes persist during restart, there is no easy way. Simplest one will be to re-install.
You can edit `/opt/mtp_proxy/releases/0.1.0/sys.config`, but it will be overwritten by every reinstall and `0.1.0` can change to other version number in the future.

> also how can i limit or view connections number( or client ips ) on each port?

This will show you number of connections to each "listener" (by name):

```bash
/opt/mtp_proxy/bin/mtp_proxy eval '[{Name, proplists:get_value(all_connections, L)} || {Name, L} <- ranch:info()].'
```

Or, if you really want "port":

```bash
/opt/mtp_proxy/bin/mtp_proxy eval '[{proplists:get_value(port, L), proplists:get_value(all_connections, L)} || {Name, L} <- ranch:info()].'
```

> cal we use one port with multi secret?

No, this is not supported and it's super inefficient. I would suggest to check `fake-tls` protocol and use `tls_allowed_domains` instead.

**Comment by seriyps** [comment]
I added better tools for configuration reload without restart in c6e6ee6f3b93e2215f8463a6fe9e0dfa0d56fb21. See https://github.com/seriyps/mtproto_proxy#apply-config-changes-without-restart

**Comment by mohamad77** [comment]
thanks
in new update,can i define policy for each portname or port?
thanks
