### ISSUE TITLE
Tls

### ISSUE THREAD

**Issue by eroxs** [seriyps/mtproto_proxy#18]
doesn't work Fake TLS  with first script ( one-line interactive installer )

**Comment by seriyps** [comment]
Hi. What exactly do not work? It doesn't finish installation or you can't connect? Can you connect with other protocols?
Can you show script output (maybe remove your IP from it)?

**Comment by eroxs** [comment]
=| 
When i run ( curl -L -o mtp_install.sh https://git.io/fj5ru && bash mtp_install.sh -p 443 -s 00000000000000000000000000000000 -t 2efcee711da26196c500cc9acfae2f4e -a dd -a tls ) 
In the end , my fake tls be :

Normal:          https://t.me/proxy?server=172.104.6.208&port=443&secret=00
000000000000000000000000000000
Secure:          https://t.me/proxy?server=172.104.6.208&port=443&secret=dd00000000000000000000000000000000
Fake-TLS hex:    https://t.me/proxy?server=172.104.6.208&port=443&secret=ee676f6f676c652e636f6d
Fake-TLS base64: https://t.me/proxy?server=172.104.6.208&port=443&secret=7mdvb2dsZS5jb20=


Its amazing ! When i want to connect in telegram with fake tls base 64 , my telegram will be hanging and then I can't start telegram again , and i must uninstall app and install again 

When i run (systemctl status ) , its running and active , 

I test another secret after run your script ( ee00000000000000000000000000000000000000001233 ) ( 7gAAAAAAAAAAAAAAAAAAAABlbi53aWtpcGVkaWEub3Jn ) 
But dont connect proxy 
I can Just connect to secure link with dd

**Comment by seriyps** [comment]
Well, TLS secrets generated by the script look wrong. I will try to fix.

**Comment by seriyps** [comment]
I updated installation script. Please try to run again:

```
curl -L -o mtp_install.sh https://git.io/fj5ru && bash mtp_install.sh -p 443 -s 00000000000000000000000000000000 -t 2efcee711da26196c500cc9acfae2f4e -a dd -a tls
```

It should print correct proxy links now.
