### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MrMstafa** [seriyps/mtproto_proxy#2]
```
===> Compiling src/mtp_down_conn.erl failed
src/mtp_down_conn.erl:37: syntax error before: ':='

src/mtp_down_conn.erl:24: type upstream_opts() undefined

Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1
--------------------------------------
src/gen_timeout.erl:33: syntax error before: ':='

src/gen_timeout.erl:39: type opts() undefined

Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1
-------------------------------------------
```
???
@seriyps

**Comment by seriyps** [comment]
Hi. Sorry for a late response. It looks like you use very old Erlang version.
1. What is your OS? You can run `cat /etc/os-release` to be able to answer this
2. Which Erlang version do you have? You can find it out by running a command `erl`. It will print a line like `Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]`

**Comment by seriyps** [comment]
Yep, the problem is that you have "Erlang/OTP 18". mtproto_proxy needs at least Erlang 20. On ubunty 18.04 it's already 20, but for Ubuntu 16.04 you may need to upgrade it to 20 or 21 from this repository https://www.erlang-solutions.com/resources/download.html
