### ISSUE TITLE
Extra random port listened by process

### ISSUE THREAD

**Issue by omawnakw** [seriyps/mtproto_proxy#20]
Hello. I'm not familiar with erlang, just configured and set up the proxy.
I've made an OS install with custom config. 
Here is what I changed in config:
```
[
 {mtproto_proxy,
  %% see src/mtproto_proxy.app.src for examples.
  %% DO NOT EDIT src/mtproto_proxy.app.src!!!
  [
    {external_ip, "172.26.1.1"},
    {allowed_protocols, [mtp_fake_tls]},
    {ports,
     [#{name => mtp_handler1,
        listen_ip => "172.26.1.1",
        port => 12343,
        secret => <<"64a7d74f4847a0249f88f316d6dd076b">>,
        tag => <<"f5f685f3e5bda7b62eaba0a4ace4d440">>}
     ]}
   ]},
```

Starting up with mtp_proxy start. Everything works fine but some extra random port get listened on all interfaces.

```
mtp_proxy eval '[{proplists:get_value(port, L), proplists:get_value(all_connections, L)} || {Name, L} <- ranch:info()].'
[{12343,3}]
mtproxy@server:~/git/MTProxy-Erlang/src$ netstat -pln|grep mtp_proxy
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:60374           0.0.0.0:*               LISTEN      22656/mtp_proxy
tcp        0      0 172.26.1.1:12343        0.0.0.0:*               LISTEN      22656/mtp_proxy
```
What is the purpose of the 60374 port here? If it's for some monitoring culd we bind it 127.0.0.1?

**Comment by seriyps** [comment]
Oh, yes, this is Erlang cluster distribution interface.  One should know secret "cookie" to be able to use it.
You can change it to only listen on localhost by editing `config/prod-vm.args` and replacing `-name ....` line with `-sname mtproto_proxy` and reinstalling the proxy.

**Comment by omawnakw** [comment]
Ok, thank you for the link. However setting it to use short name did not help me, why it should?
I've added this:
`-kernel inet_dist_use_interface "{127,0,0,1}"`
to config/prod-vm.args, rebuilt and stop/start. Now it listens on localhost.

exporting ERL_EPMD_ADDRESS=127.0.0.1 must do the same but it didn't work for me: maybe it's not inherited from bash env and need to be specified somewhere in configs.

**Comment by seriyps** [comment]
> setting it to use short name did not help me, why it should?

Oups, sorry. For some reason I was sure that this is the main difference between `name` and `sname`, but, apparently, it works in a different way.

> exporting ERL_EPMD_ADDRESS=127.0.0.1 must do the same but it didn't work for me
no, it's a different thing. epmd is a separate process and it is intended to be used for Erlang node discovery (when there are multiple Erlang nodes running on a single computer). epmd is separate systemd service and it has it's own systemd unit file https://github.com/seriyps/mtproto_proxy/blob/master/config/epmd.service (this one is installed only if there is no system-wide epmd already https://github.com/seriyps/mtproto_proxy/blob/30f7e6b9c1ef71dd3782203f32620e0cbcd8a068/Makefile#L46-L48)
