### ISSUE TITLE
problem in Centos 7.6

### ISSUE THREAD

**Issue by amidboys** [seriyps/mtproto_proxy#21]
Hello, I changed your bash code to install this code for centos, but only dd address is working, I want to use FAKE TLS. What do I do?

**Comment by amidboys** [comment]
also, I ran by docker, but it is the same

**Comment by seriyps** [comment]
Hi. Can you show what have you changed in the script and how you run it?

**Comment by amidboys** [comment]
> Hi. Can you show what have you changed in the script and how you run it?

I just use yum instead of apt. but I installed rebar3 and erlang manually and there is not erlang-nox erlang-dev for centos.

**Comment by seriyps** [comment]
I found a bug in setup script. I added support for CentOS and fixed this bug now. Please, try again! I tested it with CentOS 7 on Hetzner.

**Comment by amidboys** [comment]
> I found a bug in setup script. I added support for CentOS and fixed this bug now. Please, try again! I tested it with CentOS 7 on Hetzner.

tnx, bro, I've installed it but normal connection link does not work.

**Comment by seriyps** [comment]
"normal" is disabled if you enabled dd-only or tls-only. Is that the case? I will update the script to only show enabled links later

**Comment by amidboys** [comment]
it's ok. thanks a lot.
