### ISSUE TITLE
 Servers that do not support NAT such as azure

### ISSUE THREAD

**Issue by z991238** [seriyps/mtproto_proxy#22]
The MTP proxy is installed on azure and cannot be connected.

**Comment by seriyps** [comment]
Hi. It actually supports NAT and can autodetect it's public IP. I can run it on Scaleway for example. But it eon't work with NAT that do not preserve port numbers (none of mtproto proxies will work with such NAT). Is Azure NAT somehow special?

**Comment by z991238** [comment]
Azure's machine maps out fixed IP through NAT intranet IP address. If you do not set the intranet address in the machine during installation, this will happen. Cloud servers, including Google Cloud, need to be set up to successfully use the software. I have tried the installation of the MTP TO version, and I also need to set the IP address of the intranet server starting with 10.x in his server.

**Comment by seriyps** [comment]
Yep, sure, ping me `@seriy_ps` on telegram.

But the local IP (`10.x.x.x` one) you should put as `{listen_ip, "10.x.x.x"}` in the config (or can just use `0.0.0.0` to listen on all interfaces). External one can be auto-detected by proxy, but you can disable autodetection and hardcode it: just remove `ip_lookup_services` config and define `{external_ip, "YOUR.SERVER.EXTERNAL.IP"},`.

**Comment by seriyps** [comment]
So, after investigation we found that issue was not related to NAT, but to the fact that proxy uses `wikipedia.org` and `google.com` in TLS SNI and both are blocked in China
