### ISSUE TITLE
How to change sponsored channel?

### ISSUE THREAD

**Issue by darkdef7** [seriyps/mtproto_proxy#31]
How to change sponsored channel?

**Comment by seriyps** [comment]
You need to register your proxy in @MTProxybot and use "proxy tag" that it gives you as `ad tag` in this proxy.
How do you set ad tag depends on how have you installed the proxy.

**Comment by darkdef7** [comment]
Please tell me what I must do for this?

I follow this guide-
How to start OS-install - detailed
Install deps
Ubuntu 18.xx / Ubuntu 19.xx / Debian 10
....

**Comment by seriyps** [comment]
First:

https://github.com/seriyps/mtproto_proxy#change-default-port--secret--ad-tag

Then:

https://github.com/seriyps/mtproto_proxy#apply-config-changes-without-restart

**Comment by darkdef7** [comment]
Thanks! and tell me please how to make it autostart in ubuntu ?

**Comment by seriyps** [comment]
If you did everything as it is described in instruction, it should already autostart on reboot. This command from install instruction enables autostart: `sudo systemctl enable mtproto-proxy`

**Comment by darkdef7** [comment]
Something go wrong:
Please help!

ubuntu@ip-172-33-21-46:~$ cd mtproto_proxy/
ubuntu@ip-172-33-21-46:~/mtproto_proxy$ sudo systemctl enable mtproto-proxy
ubuntu@ip-172-33-21-46:~/mtproto_proxy$ sudo systemctl start mtproto-proxy
A dependency job for mtproto-proxy.service failed. See 'journalctl -xe' for details.

ubuntu@ip-172-33-21-46:~/mtproto_proxy$ journalctl -xe
Aug 28 07:14:16 ip-172-33-21-46 systemd[1]: Reloading.
Aug 28 07:14:16 ip-172-33-21-46 sshd[1999]: Received disconnect from 128.199.136.129 port 49592:11: Bye Bye [preauth]
Aug 28 07:14:16 ip-172-33-21-46 sshd[1999]: Disconnected from invalid user zanni 128.199.136.129 port 49592 [preauth]
Aug 28 07:14:16 ip-172-33-21-46 systemd[1]: Configuration file /etc/systemd/system/mtproto-proxy.service is marked executable. Please remove
Aug 28 07:14:16 ip-172-33-21-46 sudo[2001]: pam_unix(sudo:session): session closed for user root
Aug 28 07:16:20 ip-172-33-21-46 sudo[2042]: ubuntu : TTY=pts/0 ; PWD=/home/ubuntu/mtproto_proxy ; USER=root ; COMMAND=/bin/systemctl enabl
Aug 28 07:16:20 ip-172-33-21-46 sudo[2042]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Aug 28 07:16:20 ip-172-33-21-46 systemd[1]: Configuration file /etc/systemd/system/mtproto-proxy.service is marked executable. Please remove
Aug 28 07:16:20 ip-172-33-21-46 systemd[1]: Reloading.
Aug 28 07:16:20 ip-172-33-21-46 systemd[1]: Configuration file /etc/systemd/system/mtproto-proxy.service is marked executable. Please remove
Aug 28 07:16:20 ip-172-33-21-46 sudo[2042]: pam_unix(sudo:session): session closed for user root
Aug 28 07:16:25 ip-172-33-21-46 sudo[2068]: ubuntu : TTY=pts/0 ; PWD=/home/ubuntu/mtproto_proxy ; USER=root ; COMMAND=/bin/systemctl start
Aug 28 07:16:25 ip-172-33-21-46 sudo[2068]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Aug 28 07:16:25 ip-172-33-21-46 systemd[2071]: epmd.socket: Failed to create listening socket: Address already in use
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: epmd.socket: Failed to receive listening socket: Input/output error
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: epmd.socket: Failed to listen on sockets: Input/output error
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: epmd.socket: Failed with result 'resources'.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: Failed to listen on Erlang Port Mapper Daemon Activation Socket.
-- Subject: Unit epmd.socket has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit epmd.socket has failed.
--
-- The result is RESULT.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: Dependency failed for Erlang Port Mapper Daemon.
-- Subject: Unit epmd.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit epmd.service has failed.
--
-- The result is RESULT.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: Dependency failed for Starts the mtproto_proxy server.
-- Subject: Unit mtproto-proxy.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit mtproto-proxy.service has failed.
--
-- The result is RESULT.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: mtproto-proxy.service: Job mtproto-proxy.service/start failed with result 'dependency'.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: epmd.service: Job epmd.service/start failed with result 'dependency'.
Aug 28 07:16:25 ip-172-33-21-46 sudo[2068]: pam_unix(sudo:session): session closed for user root
Aug 28 07:17:01 ip-172-33-21-46 CRON[2080]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 28 07:17:01 ip-172-33-21-46 CRON[2087]: (root) CMD ( cd / && run-parts --report /etc/cron.hourly)
Aug 28 07:17:01 ip-172-33-21-46 CRON[2080]: pam_unix(cron:session): session closed for user root
lines 2079-2125/2125 (END)
Aug 28 07:14:16 ip-172-33-21-46 systemd[1]: Reloading.
Aug 28 07:14:16 ip-172-33-21-46 sshd[1999]: Received disconnect from 128.199.136.129 port 49592:11: Bye Bye [preauth]
Aug 28 07:14:16 ip-172-33-21-46 sshd[1999]: Disconnected from invalid user zanni 128.199.136.129 port 49592 [preauth]
Aug 28 07:14:16 ip-172-33-21-46 systemd[1]: Configuration file /etc/systemd/system/mtproto-proxy.service is marked executable. Please remove execut
Aug 28 07:14:16 ip-172-33-21-46 sudo[2001]: pam_unix(sudo:session): session closed for user root
Aug 28 07:16:20 ip-172-33-21-46 sudo[2042]: ubuntu : TTY=pts/0 ; PWD=/home/ubuntu/mtproto_proxy ; USER=root ; COMMAND=/bin/systemctl enable mtpro
Aug 28 07:16:20 ip-172-33-21-46 sudo[2042]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Aug 28 07:16:20 ip-172-33-21-46 systemd[1]: Configuration file /etc/systemd/system/mtproto-proxy.service is marked executable. Please remove execut
Aug 28 07:16:20 ip-172-33-21-46 systemd[1]: Reloading.
Aug 28 07:16:20 ip-172-33-21-46 systemd[1]: Configuration file /etc/systemd/system/mtproto-proxy.service is marked executable. Please remove execut
Aug 28 07:16:20 ip-172-33-21-46 sudo[2042]: pam_unix(sudo:session): session closed for user root
Aug 28 07:16:25 ip-172-33-21-46 sudo[2068]: ubuntu : TTY=pts/0 ; PWD=/home/ubuntu/mtproto_proxy ; USER=root ; COMMAND=/bin/systemctl start mtprot
Aug 28 07:16:25 ip-172-33-21-46 sudo[2068]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Aug 28 07:16:25 ip-172-33-21-46 systemd[2071]: epmd.socket: Failed to create listening socket: Address already in use
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: epmd.socket: Failed to receive listening socket: Input/output error
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: epmd.socket: Failed to listen on sockets: Input/output error
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: epmd.socket: Failed with result 'resources'.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: Failed to listen on Erlang Port Mapper Daemon Activation Socket.
-- Subject: Unit epmd.socket has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit epmd.socket has failed.
--
-- The result is RESULT.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: Dependency failed for Erlang Port Mapper Daemon.
-- Subject: Unit epmd.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit epmd.service has failed.
--
-- The result is RESULT.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: Dependency failed for Starts the mtproto_proxy server.
-- Subject: Unit mtproto-proxy.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit mtproto-proxy.service has failed.
--
-- The result is RESULT.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: mtproto-proxy.service: Job mtproto-proxy.service/start failed with result 'dependency'.
Aug 28 07:16:25 ip-172-33-21-46 systemd[1]: epmd.service: Job epmd.service/start failed with result 'dependency'.
Aug 28 07:16:25 ip-172-33-21-46 sudo[2068]: pam_unix(sudo:session): session closed for user root
Aug 28 07:17:01 ip-172-33-21-46 CRON[2080]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 28 07:17:01 ip-172-33-21-46 CRON[2087]: (root) CMD ( cd / && run-parts --report /etc/cron.hourly)
Aug 28 07:17:01 ip-172-33-21-46 CRON[2080]: pam_unix(cron:session): session closed for user root

**Comment by seriyps** [comment]
Seems `epmd` process is already running. Try following:

```
sudo killall epmd
sudo systemctl restart mtproto-proxy
```

**Comment by seriyps** [comment]
Btw, I created a chat in telegram to discuss erlang proxy https://t.me/erlang_mtproxy

**Comment by darkdef7** [comment]
Oh, its good! I join for future questions!

**Comment by H-MAli** [comment]
What if I want to run my proxy with no "Sponsored Channel"s?

**Comment by seriyps** [comment]
If you just want to not show ads, you can setup MTProxybot to not have
sponsored channel.
Another option is to set ad tag to random 32 digits (or 32 zeroes). It will
work just fine, but no ads will be shown.

сб, 1 февр. 2020 г., 15:33 Mohammad Ali Haghshenas <notifications@github.com
