### ISSUE TITLE
TLS Fake

### ISSUE THREAD

**Issue by ZarinNegah** [seriyps/mtproto_proxy#32]
hi
The proxy link that is with Fake Tls ( hash and base64 ) Some of the Iranian internet is not working and cannot be connected
At the beginning and after the server config
And the server is not filtered
Where's the problem?

**Comment by FreedomPrevails** [comment]
You have probably made a mistake somewhere. I can confirm this proxy works in Iran with no issues.
Dont forget that telegram client SHOULD be upgraded to the latest version, otherwise TLS proxy wont work.

**Comment by ZarinNegah** [comment]
> You have probably made a mistake somewhere. I can confirm this proxy works in Iran with no issues.
> Dont forget that telegram client SHOULD be upgraded to the latest version, otherwise TLS proxy wont work.

Thanks, the problem was resolved and the telegram was not updated
How can I connect to any user
Secret code different with this method Base64 Fake TLS
But there is a basic code secret in Configuration

**Comment by seriyps** [comment]
> How can I connect to any user
> Secret code different with this method Base64 Fake TLS
> But there is a basic code secret in Configuration
> for example
> 500 > Links with different Fake tls secret ,

Sorry, I don't understand your question

**Comment by ZarinNegah** [comment]
> > How can I connect to any user
> > Secret code different with this method Base64 Fake TLS
> > But there is a basic code secret in Configuration
> > for example
> > 500 > Links with different Fake tls secret ,
> 
> Sorry, I don't understand your question

I need 500 proxy links with different secret ( Base64 Fake tls )

**Comment by FreedomPrevails** [comment]
Theoretically I guess you can define 500 handlers with 500 different secrets, But I am not sure if it is a good idea practically.
Probably @seriyps can shed some light on this matter.

**Comment by ZarinNegah** [comment]
> Theoretically I guess you can define 500 handlers with 500 different secrets, But I am not sure if it is a good idea practically.
> Probably @seriyps can shed some light on this matter.

Thank you
Waiting for @seriyps comment

**Comment by seriyps** [comment]
@ZarinNegah it's described here: https://github.com/seriyps/mtproto_proxy#personal-proxy--multi-secret-proxy

So, you enable policy to only allow connections with certain TLS domains and generate unique domain & unique link.

**Comment by ZarinNegah** [comment]
> @ZarinNegah it's described here: https://github.com/seriyps/mtproto_proxy#personal-proxy--multi-secret-proxy
> 
> So, you enable policy to only allow connections with certain TLS domains and generate unique domain & unique link.

thank you

I didn't understand how to apply these codes
Because I don't have much knowledge of this language
You have tips for using and user the following section
https://github.com/seriyps/mtproto_proxy#personal-proxy--multi-secret-proxy
