### ISSUE TITLE
Unknown upstream & upstream sock error: etimedout

### ISSUE THREAD

**Issue by FreedomPrevails** [seriyps/mtproto_proxy#35]
I have setup a new proxy and used it a few minutes for testing myself and I can already see some errors like these in the application.log :
```
[info] <0.623.0>@mtp_down_conn:handle_upstream_closed:240 Unknown upstream <0.721.0>
[warning] <0.719.0>@mtp_handler:handle_info:195 upstream sock error: etimedout
```
When it says upstream, does it mean connections to telegram proxy servers ?
Is this normal ?

**Comment by seriyps** [comment]
I think in my implementation names for upstream and downstream are reversed compared to common meanings. In my code upstream is the part that handles telegram client connections and downstream is part that handles connections from proxy to telegram server.
Should probably rename to "frontend" and "backend"...

**Comment by seriyps** [comment]
> `[info] <0.623.0>@mtp_down_conn:handle_upstream_closed:240 Unknown upstream <0.721.0>`

This is more or less ok. Some harmless race-condition

> `[warning] <0.719.0>@mtp_handler:handle_info:195 upstream sock error: etimedout`

this most likely mean that telegram client was disconnected abnormally (eg, lost wifi signal). It's also more or less ok

**Comment by FreedomPrevails** [comment]
Thanks !
