### ISSUE TITLE
policy

### ISSUE THREAD

**Issue by mohamad77** [seriyps/mtproto_proxy#36]
Hello
How can i define policy for each portname?
Thanks

**Comment by seriyps** [comment]
You mean different policy for each port? If yes, unfortunately it is not supported at the moment.
If you describe your usecase in more details, maybe I will suggest some solution. What do you want to achieve?

**Comment by mohamad77** [comment]
thanks for your reply
i wanna limit connections for each portname
thanks

**Comment by seriyps** [comment]
number of connections? Or tls domains?
more details you provide, more chance I will be able to help.

**Comment by mohamad77** [comment]
number of connections
thanks

**Comment by seriyps** [comment]
Well, if you need to limit only number of connections to a port and don't need to limit by client's IP etc, you can run this:

```
/opt/mtp_proxy/bin eval 'ranch:set_max_connections(port_name, 12345)'
```

replace `port_name` with port you need.

But it will be reset after restart.
Unfortunately, there is no better solution right now.
