### ISSUE TITLE
Connection issues 

### ISSUE THREAD

**Issue by Alien-hide** [seriyps/mtproto_proxy#37]
When i connect to proxy, in log file on server make record: protocol_error tls_invalid_digest
I use in client secret eg:  ee(+)d1d908dd913f9b15cacf3e89ec7de74ac2351d4435d8a0215f75e1b62eadfd45 (generate after container start)
how i make correct secret? 
old work secret eg: 9a1be70073b89885774e6617e9870ce0

**Comment by FreedomPrevails** [comment]
use this command to generate a valid secret : `openssl rand -hex 16`

**Comment by Alien-hide** [comment]
But this is not base64, how get secret this type?

**Comment by seriyps** [comment]
Can you show which secret you have in your config file `prod-sys.config` and which one you use in your proxy link?
`tls_invalid_digest` most likely means that secret is invalid.

It's better to not use base64 secret, because, unfortunately, they work different in iOS and Android

**Comment by Alien-hide** [comment]
in /opt/mtp_proxy/releases/0.1.0 # sys.config default value. 
I use docker container, send secret as key -s 9a1be70073b89885774e6617e9870ce0

>It's better to not use base64 secret, because, unfortunately, they work different in iOS and Android
Ok, but how use TLS and ee prefix? (stable pc and ios client regent my secret with "ee")

**Comment by seriyps** [comment]
Which versions exactly do you have?
Maybe it will be easier to discuss in Telegram https://t.me/erlang_mtproxy

**Comment by Alien-hide** [comment]
The problem was that I didnt add the hex domain after the secret like this:
ee<secret><hex domain at least 8 chars> (all_with_out_space)
