### ISSUE TITLE
What is storage cleaned ?

### ISSUE THREAD

**Issue by FreedomPrevails** [seriyps/mtproto_proxy#38]
Hi,
On regular intervals, I am receiving a message like this in log :
`[info] <0.633.0>@mtp_session_storage:handle_info:112 storage cleaned: []; remaining: 3129`
I got suspicious of it because the remaining number is just going up and never decreases.
Also the [] seems to show an array which is empty !
Can you please explain what exactly it does and is this behavior normal ?

**Comment by seriyps** [comment]
It is a periodic task to clean "replay protection" session storage. The number will be +1 each time you have a new connection and will be reclaimed according to the rules defined in `replay_check_session_storage_opts` config:

https://github.com/seriyps/mtproto_proxy/blob/c18cd95f5109635e712660beb4fa726f3f5ba468/src/mtproto_proxy.app.src#L103-L119

So, by default, this number should not grow above 4mln/512mb and it should also remove records that are older than 6 hours.

On proxy servers with low load probably only `max_age_minutes` will be ever triggered, but on gigh-loaded ones one of `max_memory` or `max_items`. But yep, this cleanup is performed not instantly, but once per minute.

**Comment by FreedomPrevails** [comment]
Thanks !
