### ISSUE TITLE
Doesn't work on Telegram X

### ISSUE THREAD

**Issue by LorenzoGreco83** [seriyps/mtproto_proxy#39]
Hello

it doesn't work on Telegram X. How could I fix it?

**Comment by seriyps** [comment]
Hi. Fake-tls or all protocols?
Which version of telegram X do you use exactly?

**Comment by LorenzoGreco83** [comment]
All protocols

I have the latest on android

Telegram X 0.21.9.1172-arm64-v8a

**Comment by seriyps** [comment]
But works with official Telegram?

**Comment by LorenzoGreco83** [comment]
Yes it works fine with it

**Comment by LorenzoGreco83** [comment]
any update?

**Comment by seriyps** [comment]
I don't know to be honest.
Do you use `ee` secret ot base64 secret?
Can you connect to other fake-tls proxies or this problem exists only for your own one?

**Comment by LorenzoGreco83** [comment]
I've tried all fiur types of mtproto. They didn't work.
There are some proxies on MTProtoProxies channel on telegram, they work fine on Telegram X and their secret start with "dd".

**Comment by z991238** [comment]
The official Telegram X is no longer maintained. Should not be connected in support of TLS mode
