### ISSUE TITLE
Crash on launch on macOS

### ISSUE THREAD

**Issue by sirburpalot** [seriyps/mtproto_proxy#41]
I'm trying to run mtproto_proxy in Docker on macOS Catalina as described in the instructions, and I'm getting an error. Please see the crash report in the attachment.

[mtproto_proxy.log](https://github.com/seriyps/mtproto_proxy/files/3632900/mtproto_proxy.log)

**Comment by seriyps** [comment]
My guess is that you are trying to connect from your hone computer that is
behind the NAT that doesn't preserve tcp port numbers.
Proxy doesn't work in such conditions because tcp port is included in
encryption key.

чт, 19 сент. 2019 г., 21:42 sirburpalot <notifications@github.com>:

**Comment by sirburpalot** [comment]
I am indeed trying to connect from a home computer that's behind a NAT, but other MTProto proxies seem to work fine. Is this not something that can be fixed?

**Comment by seriyps** [comment]
@sirburpalot which proxies do work fine? Python / MTG / official?

**Comment by sirburpalot** [comment]
@seriyps, Python.

**Comment by seriyps** [comment]
python proxy disables advertizing and uses another protocol in such conditions. This is not implemented in Erlang proxy and there is no plans to implement that.
