### ISSUE TITLE
config

### ISSUE THREAD

**Issue by NasaKHw** [seriyps/mtproto_proxy#43]
hi

{max_connections, 128000},
{upstream_socket_buffer_size, 20480},
{downstream_socket_buffer_size, 512000},
{replay_check_session_storage, on},
{replay_check_session_storage_opts,
  {max_memory_mb => 25048,
    max_age_minutes => 1440}},
solved

**Comment by seriyps** [comment]
https://github.com/seriyps/mtproto_proxy/blob/d9d812e9cf9e028cf3404d5f6aa51bfe7b4a3597/config/sys.config.example#L7

line 7, not in `sys.config.example` but `prod-sys.config`

**Comment by NasaKHw** [comment]
we still have 32%cpu usage and 3% ram usage

**Comment by seriyps** [comment]
yep, those configs only affect performance slightly. But there is not much we can do: most of CPU load comes from AES encryption.

**Comment by NasaKHw** [comment]
thanks a lot
but what is your suggestion config for this server : i7 8400 / ram 32

**Comment by seriyps** [comment]
I don't think changing the default config may noticeably reduce CPU usage, so, either leave it as is, or change to what you have in the README. It may give you a few percent of difference. I personally use the same almost default config on all my servers. The main options that can affect performance are `upstream_socket_buffer_size` and `downstream_socket_buffer_size`.

**Comment by NasaKHw** [comment]
root@ip-172-26-4-223:~# /opt/mtp_proxy/bin/mtp_proxy eval 'lists:sum([proplists:get_value(all_connections, L) || {_, L} <- ranch:info()]).'
Node is not running!

**Comment by seriyps** [comment]
`ss -s` will show number of open sockets, but it is 5-10% higher than number of client connections
