### ISSUE TITLE
crash debian9 and debian10 both try

### ISSUE THREAD

**Issue by chanho0** [seriyps/mtproto_proxy#44]
Exec: /opt/mtp_proxy/erts-10.3.5.6/bin/erlexec -noshell -noinput +Bd -boot /opt/mtp_proxy/releases/0.1.0/mtp_proxy -mode embedded -boot_var ERTS_LIB_DIR /opt/mtp_proxy/lib -config /opt/mtp_proxy/releases/0.1.0/sys.config -args_file /opt/mtp_proxy/releases/0.1.0/vm.args -- foreground -mtproto_proxy allowed_protocols [mtp_fake_tls,mtp_secure] -mtproto_proxy ports [#{name => mtproto_proxy, port => 5555, secret => <<"5e0f1916a79433f3bc26cca1799dff63">>, tag => <<"837e719d9d328a07105dad7997367a46">>}]
Root: /opt/mtp_proxy
/opt/mtp_proxy
=SUPERVISOR REPORT==== 17-Dec-2019::16:51:21.359214 ===
    supervisor: {local,mtproto_proxy_sup}
    errorContext: start_error
    reason: {{badmatch,
                 {error,
                     {failed_connect,
                         [{to_address,{"core.telegram.org",443}},
                          {inet,[inet],timeout}]}}},
             [{mtp_config,http_get,1,
                  [{file,"/build/mtproto_proxy/src/mtp_config.erl"},
                   {line,277}]},
              {mtp_config,update_key,1,
                  [{file,"/build/mtproto_proxy/src/mtp_config.erl"},
                   {line,192}]},
              {mtp_config,update,2,
                  [{file,"/build/mtproto_proxy/src/mtp_config.erl"},
                   {line,181}]},
              {mtp_config,init,1,
                  [{file,"/build/mtproto_proxy/src/mtp_config.erl"},
                   {line,144}]},
              {gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},
              {gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},
              {proc_lib,init_p_do_apply,3,
                  [{file,"proc_lib.erl"},{line,249}]}]}
    offender: [{pid,undefined},
               {id,mtp_config},
               {mfargs,{mtp_config,start_link,[]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
=CRASH REPORT==== 17-Dec-2019::16:51:21.358782 ===
  crasher:
    initial call: mtp_config:init/1
    pid: <0.587.0>
    registered_name: []
    exception error: no match of right hand side value 
                     {error,
                         {failed_connect,
                             [{to_address,{"core.telegram.org",443}},
                              {inet,[inet],timeout}]}}
      in function  mtp_config:http_get/1 (/build/mtproto_proxy/src/mtp_config.erl, line 277)
      in call from mtp_config:update_key/1 (/build/mtproto_proxy/src/mtp_config.erl, line 192)
      in call from mtp_config:update/2 (/build/mtproto_proxy/src/mtp_config.erl, line 181)
      in call from mtp_config:init/1 (/build/mtproto_proxy/src/mtp_config.erl, line 144)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [mtproto_proxy_sup,<0.583.0>]
    message_queue_len: 0
    messages: []
    links: [<0.584.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 22919
  neighbours:

=CRASH REPORT==== 17-Dec-2019::16:51:21.366260 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.582.0>
    registered_name: []
    exception exit: {bad_return,
                     {{mtproto_proxy_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,mtp_config,
                            {{badmatch,
                              {error,
                               {failed_connect,
                                [{to_address,{"core.telegram.org",443}},
                                 {inet,[inet],timeout}]}}},
                             [{mtp_config,http_get,1,
                               [{file,
                                 "/build/mtproto_proxy/src/mtp_config.erl"},
                                {line,277}]},
                              {mtp_config,update_key,1,
                               [{file,
                                 "/build/mtproto_proxy/src/mtp_config.erl"},
                                {line,192}]},
                              {mtp_config,update,2,
                               [{file,
                                 "/build/mtproto_proxy/src/mtp_config.erl"},
                                {line,181}]},
                              {mtp_config,init,1,
                               [{file,
                                 "/build/mtproto_proxy/src/mtp_config.erl"},
                                {line,144}]},
                              {gen_server,init_it,2,
                               [{file,"gen_server.erl"},{line,374}]},
                              {gen_server,init_it,6,
                               [{file,"gen_server.erl"},{line,342}]},
                              {proc_lib,init_p_do_apply,3,
                               [{file,"proc_lib.erl"},{line,249}]}]}}}}},
                        [{mtproto_proxy_app,start,2,
                          [{file,
                            "/build/mtproto_proxy/src/mtproto_proxy_app.erl"},
                           {line,34}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.581.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.583.0>,normal}]
    links: [<0.581.0>,<0.479.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 275
  neighbours:

=INFO REPORT==== 17-Dec-2019::16:51:21.370606 ===
    application: mtproto_proxy
    exited: {bad_return,
             {{mtproto_proxy_app,start,[normal,[]]},
              {'EXIT',
               {{badmatch,
                 {error,
                  {shutdown,
                   {failed_to_start_child,mtp_config,
                    {{badmatch,
                      {error,
                       {failed_connect,
                        [{to_address,{"core.telegram.org",443}},
                         {inet,[inet],timeout}]}}},
                     [{mtp_config,http_get,1,
                       [{file,"/build/mtproto_proxy/src/mtp_config.erl"},
                        {line,277}]},
                      {mtp_config,update_key,1,
                       [{file,"/build/mtproto_proxy/src/mtp_config.erl"},
                        {line,192}]},
                      {mtp_config,update,2,
                       [{file,"/build/mtproto_proxy/src/mtp_config.erl"},
                        {line,181}]},
                      {mtp_config,init,1,
                       [{file,"/build/mtproto_proxy/src/mtp_config.erl"},
                        {line,144}]},
                      {gen_server,init_it,2,
                       [{file,"gen_server.erl"},{line,374}]},
                      {gen_server,init_it,6,
                       [{file,"gen_server.erl"},{line,342}]},
                      {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,249}]}]}}}}},
                [{mtproto_proxy_app,start,2,
                  [{file,"/build/mtproto_proxy/src/mtproto_proxy_app.erl"},
                   {line,34}]},
                 {application_master,start_it_old,4,
                  [{file,"application_master.erl"},{line,277}]}]}}}}
    type: permanent
=SUPERVISOR REPORT==== 17-Dec-2019::16:51:21.410506 ===
    supervisor: {local,gr_counter_sup}
    errorContext: child_terminated
    reason: killed
    offender: [{pid,<0.550.0>},
               {id,gr_lager_default_tracer_counters},
               {mfargs,{gr_counter,start_link,
                                   [gr_lager_default_tracer_counters]}},
               {restart_type,transient},
               {shutdown,brutal_kill},
               {child_type,worker}]
=SUPERVISOR REPORT==== 17-Dec-2019::16:51:21.410904 ===
    supervisor: {local,gr_param_sup}
    errorContext: child_terminated
    reason: killed
    offender: [{pid,<0.549.0>},
               {id,gr_lager_default_tracer_params},
               {mfargs,{gr_param,start_link,[gr_lager_default_tracer_params]}},
               {restart_type,transient},
               {shutdown,brutal_kill},
               {child_type,worker}]
{"Kernel pid terminated",application_controller,"{application_start_failure,mtproto_proxy,{bad_return,{{mtproto_proxy_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,mtp_config,{{badmatch,{error,{failed_connect,[{to_address,{\"core.telegram.org\",443}},{inet,[inet],timeout}]}}},[{mtp_config,http_get,1,[{file,\"/build/mtproto_proxy/src/mtp_config.erl\"},{line,277}]},{mtp_config,update_key,1,[{file,\"/build/mtproto_proxy/src/mtp_config.erl\"},{line,192}]},{mtp_config,update,2,[{file,\"/build/mtproto_proxy/src/mtp_config.erl\"},{line,181}]},{mtp_config,init,1,[{file,\"/build/mtproto_proxy/src/mtp_config.erl\"},{line,144}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}}}},[{mtproto_proxy_app,start,2,[{file,\"/build/mtproto_proxy/src/mtproto_proxy_app.erl\"},{line,34}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,277}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,mtproto_proxy,{bad_return,{{mtproto_proxy_app,start,[normal,[]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,m

Crash dump is being written to: erl_crash.dump...done

**Comment by seriyps** [comment]
Seems https://core.telegram.org:443 is not accessible from your server
