### ISSUE TITLE
How can get tables data?

### ISSUE THREAD

**Issue by sr-mehti** [seriyps/mtproto_proxy#47]
hi,how can see black list table data from bash?

**Comment by seriyps** [comment]
Well, you can try
```
/opt/mtp_proxy/bin/mtp_proxy eval 'ets:tab2list(mtp_policy_table).'
```

but it will give you data in internal format. Are you interested in IP blacklist?

**Comment by sr-mehti** [comment]
Thanks, I only asked to see blocked ip's. I meant this given code which solved my issue.
