### ISSUE TITLE
Base64 Secret Problem

### ISSUE THREAD

**Issue by sr-mehti** [seriyps/mtproto_proxy#48]
hi
In Apple phones, Users can establish connection through "/" base64 secrets, But not in Android, Is it possible to achieve it in android?
Actually, Users can replace " _ " with " / " to establish connection But i want them to connect through this " / ".

**Comment by seriyps** [comment]
Unfortunately, it's not possible to make both clients interpret `/` and `_` in the same way from proxy side. Telegram devs should fix this in apps.
But you can try to generate secrets that doesn't contain those symbols or use hex secrets.
