### ISSUE TITLE
Accpect connections only from certain domain

### ISSUE THREAD

**Issue by sr-mehti** [seriyps/mtproto_proxy#49]
hi,i want users connect to proxy only with my domain and dont accpect connections from direct ip or other domains.
Is this possible?

**Comment by seriyps** [comment]
Hi. No, this is not possible.

**Comment by sr-mehti** [comment]
Ok is there a way to drop or reject clients that connect to my server with a wrong SECRET ?

**Comment by seriyps** [comment]
Well, it is not possible to connect with wrong secret.
