### ISSUE TITLE
fake tls for ipv6

### ISSUE THREAD

**Issue by iPurya** [seriyps/mtproto_proxy#51]
hey i edit config file and put my ipv6 but i can not connect proxy with ipv6 (ipv4 is working..)..
how can i create fake tls for ipv6 ?

**Comment by seriyps** [comment]
Hi. Have you checked this section in README?
https://github.com/seriyps/mtproto_proxy/blob/master/README.md#ipv6

пн, 17 февр. 2020 г., 21:08 iPurya <notifications@github.com>:
