### ISSUE TITLE
question about performance?

### ISSUE THREAD

**Issue by khoshroomahdi** [seriyps/mtproto_proxy#52]
ex: how many user can use that with 1 core cpu and 1 gig ram?
is there anywy to use it in windows server?

**Comment by seriyps** [comment]
1. Well, there might be quite a lot, but it depends on how comfortably you want them to feel. When CPU is fully saturated there will be some noticeable slowdown in media download. I would say 5-8k connections should be fine. But also depends on CPU type / speed.
2. It definitely should be possible to install on Windows, but I never tried and don't have any good recipe. You may try to install via docker.

**Comment by abbasdezaki** [comment]
hey, how many connection it can handle with 8v cpu and 32gb ram (server is from lightsail amazon)?

**Comment by seriyps** [comment]
I would say 40-50k connections (each client creates 2-3 connections)
