### ISSUE TITLE
How to create multi port and multi secret proxies in fake tls  ?

### ISSUE THREAD

**Issue by Rafeghha** [seriyps/mtproto_proxy#54]
How to create multi port and multi secret proxies in fake tls  ? Just 1 Server .

sample [MTproxy ](https://github.com/TelegramMessenger/MTProxy) Suorce : 

group1 
cd ~/MTProxy/objs/bin && ./mtproto-proxy -u group1 -p 7777 -H 6160,1369,5183,1406,3730,9571,3670,8225,1227,2893,1526 -S 373020c2a6f1b0b6brtb2998b22b02cd8 -P deb769a5ee810d8dd732b2f79a4d69283 --aes-pwd proxy-secret proxy-multi.conf -M 1 -C 1000 -c 1000

group2

cd ~/MTProxy/objs/bin && ./mtproto-proxy -u group2 -p 7777 -H 5699,4962,7238,4127,2148,4669,5127,9938,1277,1666,5588,7825,1645,3822,3932,7053,1368,5773,8005,8297,7863,8747,6009 -S ccb5131df07469912c910df1d5321dbb -P deb769a5a810d8dd732bff79a4d69283 --aes-pwd proxy-secret proxy-multi.conf -M 1 -C 1000 -c 1000

plz help me .

best regards

**Comment by seriyps** [comment]
I think it's explained here: https://github.com/seriyps/mtproto_proxy#listen-on-multiple-ports--ips
