### ISSUE TITLE
protocol_error disabled_protocol mtp_abridged

### ISSUE THREAD

**Issue by Katerou22** [seriyps/mtproto_proxy#56]
Whats this is meaning? i see this on logs,
proxy not connecting and not working
but when i disable tls mode and dd, proxy connected but not transfering data
ubuntu 18.4 im using and ufw disabled

**Comment by seriyps** [comment]
this message "disabled_protocol mtp_abridged" means you are trying to connect with old (non-randomized and not fake-tls mode).
Maybe you only enabled `fake-tls` or `dd`-mode, but using proxy-link without `dd` or `ee`? Do you use official client?

**Comment by Katerou22** [comment]
Nah dude, im using updated official telegram desktop
and im trying to connect with normal link generated,
sometimes connected but not transferring any data to telegram sometimes not connected totally

**Comment by Katerou22** [comment]
Im sure my ip is not blocked cause i have openconnect and it connects fine

**Comment by seriyps** [comment]
Sorry, I have no idea... You can try to discuss in the telegram group: https://t.me/erlang_mtproxy
