### ISSUE TITLE
Make API call exists public?

### ISSUE THREAD

**Issue by danielsz** [seriyps/mtproto_proxy#65]
It would be nice to be able to use the API call at https://github.com/seriyps/mtproto_proxy/blob/5c8cc0c50ff577b78db3693420d16c11560b3dfe/src/mtp_policy_table.erl#L44

Which would allow us to use like `add` and `del`.
```
/opt/mtp_proxy/bin/mtp_proxy eval 'mtp_policy_table:exists(customer_domains, "my-client1.example.com").'
```

Currently it seems to always return false.

**Comment by seriyps** [comment]
Your example always returns false because `mtp_policy_table:exists` takes already normalized value as 2nd argument and for "tls_domain" normalized value is Erlang's binary like `<<"my-client1.example.com">>`, not `"my-client1.example.com"`.

it more generic way of usig in would be

```
/opt/mtp_proxy/bin/mtp_proxy eval 'mtp_policy_table:exists(customer_domains, mtp_policy:convert(tls_domain, "my-client1.example.com")).'
```

**Comment by danielsz** [comment]
Awesome. Thank you for the explanation!
